format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$character"""

right_format = """
$git_branch\
$git_state\
$git_status\
$python"""

[username]
format = "[$user]($style)"
style_user = "bold red"

[hostname]
format = "[@$hostname ]($style)"
style = "bold red"

[time]
disabled = false
format = '[$time]($style) '
style = "bold white"
time_format = '%H:%M'

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = '[git:\($branch\)]($style)'
#style = "#C2F67C"
style = "bold green"

[git_status]
format = "$ahead_behind [[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "bold cyan"
# conflicted = "​"
# untracked = ""
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "[!${count}](green)"
untracked = "[?${count}](red)"
staged = "+${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold red"

[cmd_duration]
format = "[$duration]($style) "
style = "dimmed white"

[python]
#pyenv_version_name = true
style = "white"
